#!/usr/bin/env bash
# One-shot: two Hermes profiles (jerme + archap), Telegram .env, skills, gateway install.
#
# Prereq: revoke any bot token ever pasted in chat; create fresh tokens in @BotFather.
#
# Usage (tokens only in your shell, never committed):
#   export JERME_TELEGRAM_BOT_TOKEN='...'
#   export ARCHAP_TELEGRAM_BOT_TOKEN='...'
#   bash scripts/hermes_bootstrap_dual_telegram.sh
#
# Optional:
#   export START_GATEWAYS=1     # also: hermes -p jerme gateway start && hermes -p archap gateway start
#   export INSTALL_SKILLS=1    # default 1: bash scripts/install_hermes_skills.sh productivity

set -euo pipefail

if ! command -v hermes >/dev/null 2>&1; then
  echo "error: hermes not on PATH" >&2
  exit 1
fi

if [[ -z "${JERME_TELEGRAM_BOT_TOKEN:-}" || -z "${ARCHAP_TELEGRAM_BOT_TOKEN:-}" ]]; then
  echo "error: set JERME_TELEGRAM_BOT_TOKEN and ARCHAP_TELEGRAM_BOT_TOKEN in the environment" >&2
  exit 1
fi

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

write_telegram_env() {
  local dest="$1"
  local token="$2"
  mkdir -p "$(dirname "$dest")"
  umask 077
  cat >"$dest" <<EOF
# Generated by scripts/hermes_bootstrap_dual_telegram.sh — tighten before production.
TELEGRAM_BOT_TOKEN=${token}
# Open DMs/groups: literal asterisk, not the word "everyone"
TELEGRAM_ALLOWED_USERS=*
# Redundant but explicit; Hermes honors either this or * in the allowlist
TELEGRAM_ALLOW_ALL_USERS=true
# Set when you pick a delivery target, e.g. your numeric user id for cron → Telegram
# TELEGRAM_HOME_CHANNEL=
EOF
  chmod 600 "$dest"
}

ensure_profile() {
  local name="$1"
  if [[ ! -d "$HOME/.hermes/profiles/$name" ]]; then
    echo "→ profile create $name"
    hermes profile create "$name" --no-skills
  else
    echo "→ profile $name already exists"
  fi
}

ensure_profile jerme
ensure_profile archap

write_telegram_env "$HOME/.hermes/profiles/jerme/.env" "$JERME_TELEGRAM_BOT_TOKEN"
write_telegram_env "$HOME/.hermes/profiles/archap/.env" "$ARCHAP_TELEGRAM_BOT_TOKEN"

if [[ "${INSTALL_SKILLS:-1}" == "1" ]]; then
  echo "→ install Hermes skills (productivity)"
  (cd "$REPO_ROOT" && bash scripts/install_hermes_skills.sh productivity)
fi

echo "→ gateway install (jerme)"
hermes -p jerme gateway install
echo "→ gateway install (archap)"
hermes -p archap gateway install

if [[ "${START_GATEWAYS:-}" == "1" ]]; then
  echo "→ gateway start (both)"
  hermes -p jerme gateway start || true
  hermes -p archap gateway start || true
else
  echo "→ gateways installed; start with: hermes -p jerme gateway start && hermes -p archap gateway start"
fi

echo
echo "Done. Verify:"
echo "  hermes -p jerme gateway status"
echo "  hermes -p archap gateway status"
