#!/usr/bin/env bash
# Install all Hermes skills in `hermes/skills/<category>/<skill>/` into the
# user's Hermes skills directory so Hermes picks them up on its next scan.
#
# Default destination: ~/.hermes/skills/<category>/
# Override with HERMES_SKILLS_DIR=/some/path.
#
# Idempotent. Uses `rsync -a --delete` per skill so removing a file in-repo
# also removes it from the install (keeps the directories in sync).
#
# Usage:
#   bash scripts/install_hermes_skills.sh                 # install all
#   bash scripts/install_hermes_skills.sh research        # one category only
#   bash scripts/install_hermes_skills.sh research/luma-gtm-harvest   # one skill
#   bash scripts/install_hermes_skills.sh --dry-run       # show what would change

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC_ROOT="$ROOT/hermes/skills"
DEST_ROOT="${HERMES_SKILLS_DIR:-$HOME/.hermes/skills}"

if [[ ! -d "$SRC_ROOT" ]]; then
  echo "error: no hermes/skills/ directory at repo root" >&2
  exit 1
fi

DRY=""
if [[ "${1:-}" == "--dry-run" ]]; then
  DRY="-n"
  shift
fi

TARGET="${1:-}"   # optional: "research" or "research/luma-gtm-harvest"

shopt -s nullglob

declare -a CATEGORIES
if [[ -n "$TARGET" && "$TARGET" != */* ]]; then
  CATEGORIES=("$TARGET")
else
  for d in "$SRC_ROOT"/*/; do
    CATEGORIES+=("$(basename "$d")")
  done
fi

mkdir -p "$DEST_ROOT"

installed_count=0
for cat in "${CATEGORIES[@]}"; do
  cat_src="$SRC_ROOT/$cat"
  cat_dest="$DEST_ROOT/$cat"
  if [[ ! -d "$cat_src" ]]; then
    echo "skip: $cat (not a category in repo)"
    continue
  fi
  mkdir -p "$cat_dest"

  for skill_src in "$cat_src"/*/; do
    skill_name="$(basename "$skill_src")"
    if [[ -n "$TARGET" && "$TARGET" == */* ]]; then
      want="${TARGET#*/}"
      [[ "$skill_name" != "$want" ]] && continue
    fi
    skill_dest="$cat_dest/$skill_name"
    echo "→ $cat/$skill_name"
    rsync -a $DRY --delete "$skill_src" "$skill_dest"
    installed_count=$((installed_count + 1))
  done
done

if [[ -n "$DRY" ]]; then
  echo
  echo "Dry-run: $installed_count skill(s) would be installed/refreshed at $DEST_ROOT"
else
  # Write a paths config alongside the research/ skills so any skill that
  # needs the repo root or .env can `source` it instead of hardcoding.
  if [[ -d "$DEST_ROOT/research" ]]; then
    PATHS_FILE="$DEST_ROOT/research/_growth_hacker_paths.env"
    cat > "$PATHS_FILE" <<EOF
# Auto-generated by scripts/install_hermes_skills.sh — re-run to refresh.
# Source from a SKILL: . "\$(dirname "\$0")/../_growth_hacker_paths.env"
GROWTH_HACKER_REPO="$ROOT"
GROWTH_HACKER_ENV="$ROOT/.env"
GROWTH_HACKER_DATA="$ROOT/.gstack"
GROWTH_HACKER_LUMA_RUNS="$ROOT/.gstack/luma/runs"
GROWTH_HACKER_SPECTER_SESSION="$ROOT/.gstack/specter"
GROWTH_HACKER_LUMA_SESSION="$ROOT/.gstack/luma/session"
EOF
    echo "→ research/_growth_hacker_paths.env  (REPO=$ROOT)"
  fi
  echo
  echo "Installed $installed_count skill(s) at $DEST_ROOT"
  echo "Re-open Hermes or start a new session if your build caches the skill index."
fi
